services:
  - type: web
    name: mpp-examen
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 